plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/macm4_jaepolee/workspace/token-calculator/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]